services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - redis
    volumes:
      - ./:/home/snail
  redis:
    image: "redis:alpine"
    hostname: redis.snail
    ports:
      - "6379:6379"
