# fly.toml app configuration file generated for snail on 2023-09-28T22:08:40-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "snail"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
